# Generated by Django 5.0.6 on 2024-06-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='parametros_variaveis',
            field=models.CharField(max_length=255),
        ),
    ]
