# Generated by Django 5.0.6 on 2024-06-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_endereco_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='parametros_variaveis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
