# Generated by Django 5.0.6 on 2024-06-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_equipamento_parametros_variaveis'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='endereco',
            constraint=models.UniqueConstraint(fields=('cliente', 'cep', 'numero'), name='unique address for cliente'),
        ),
    ]
