# Generated by Django 5.0.6 on 2024-06-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_created_by_cliente_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='id',
            field=models.AutoField(editable=False, help_text='Identificador único do equipamento', primary_key=True, serialize=False, unique=True),
        ),
    ]
