# Generated by Django 5.0.6 on 2024-06-05 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_created_by_cliente_updated_by_and_more'),
        ('servicos', '0002_alter_atividade_previsao_finalizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.equipamento'),
        ),
    ]
