# Generated by Django 5.0.6 on 2024-06-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_servico_procurar_por_servico_solicitado_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'permissions': (('pode_revisar', 'Pode revisar uma atividade'), ('pode_publicar', 'Pode publicar uma atividade'), ('pode_visualizar_planilha', 'Permite visualizar a planilha de atividades.'))},
        ),
    ]
